/* Generated By:JJTree: Do not edit this line. ASTBreakFunction.java */

package com.lolcode.parser;

public class ASTBreakFunction extends SimpleNode {
    public ASTBreakFunction(int id) {
        super(id);
    }

    public ASTBreakFunction(LolCode p, int id) {
        super(p, id);
    }

    public void interpret(com.lolcode.Runtime runtime) {
        jjtGetChild(0).interpret(runtime);
        if ((Boolean) runtime.pop()) {
            runtime.unwind++;
        }
    }
}
