/* Generated By:JJTree: Do not edit this line. ASTRequire.java */

package com.lolcode.parser;

import com.lolcode.LolRuntimeException;

public class ASTRequire extends SimpleNode {
    public String resource;

    public ASTRequire(int id) {
        super(id);
    }

    public ASTRequire(LolCode p, int id) {
        super(p, id);
    }


    public void interpret(com.lolcode.Runtime runtime) {
        if ("STDIO".equals(resource)) {
            return;
        }
        throw new LolRuntimeException("HAS NO " + resource);
    }
}
