/* Generated By:JJTree: Do not edit this line. ASTBoolExpression.java */

package com.lolcode.parser;

public class ASTBoolExpression extends SimpleNode {

    String name;
    int value;

    public ASTBoolExpression(int id) {
        super(id);
    }

    public ASTBoolExpression(LolCode p, int id) {
        super(p, id);
    }

    public void interpret(com.lolcode.Runtime runtime) {
        int j = (Integer) runtime.getVar(name);
        runtime.push(j > value);
    }
}
