/* Generated By:JJTree: Do not edit this line. ASTDefineVariable.java */

package com.lolcode.parser;

import com.lolcode.LolRuntimeException;

/**
 * LOLCODE has a single global namespace for variables.  When a variable is declared, it's inserted into the
 * runtime's variable set.  If the variable is already defined, a runtime exception will occur.
 */
public class ASTDefineVariable extends SimpleNode {

    String name;

    public ASTDefineVariable(int id) {
        super(id);
    }

    public ASTDefineVariable(LolCode p, int id) {
        super(p, id);
    }

    public void interpret(com.lolcode.Runtime runtime) {

        if (runtime.variables.containsKey(name)) {
            throw new LolRuntimeException("ALREADY HAS " + name);
        }
        runtime.variables.put(name, 0);
    }
}
