/* Generated By:JJTree: Do not edit this line. ASTIncrFunction.java */

package com.lolcode.parser;

public class ASTIncrFunction extends SimpleNode {
    public String name;
    public int value;

    public ASTIncrFunction(int id) {
        super(id);
    }

    public ASTIncrFunction(LolCode p, int id) {
        super(p, id);
    }

    public void interpret(com.lolcode.Runtime runtime) {
        int i = (Integer) runtime.getVar(name);
        i += value;
        runtime.variables.put(name, i);
    }
}
