/* Generated By:JJTree: Do not edit this line. ASTLoop.java */

package com.lolcode.parser;

public class ASTLoop extends SimpleNode {
    public ASTLoop(int id) {
        super(id);
    }

    public ASTLoop(LolCode p, int id) {
        super(p, id);
    }

    public void interpret(com.lolcode.Runtime runtime) {
        while (runtime.unwind == 0) {
            int k = jjtGetNumChildren();

            for (int i = 0; i < k; i++)
                jjtGetChild(i).interpret(runtime);
        }
        runtime.unwind--;
    }
}
