/* Generated By:JJTree: Do not edit this line. ASTWrite.java */

package com.lolcode.parser;

import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;

public class ASTWrite extends SimpleNode {
    public ASTWrite(int id) {
        super(id);
    }

    public ASTWrite(LolCode p, int id) {
        super(p, id);
    }


    private final List<Object> items = new ArrayList<Object>();
    private boolean visible;

    public boolean isVisible() {
        return visible;
    }

    public void setVisible(boolean visible) {
        this.visible = visible;
    }

    public void add(Object item) {
        items.add(item);
    }

    public void interpret(com.lolcode.Runtime runtime) {
        PrintStream stream = visible ? runtime.out() : runtime.err();
        for (Object item : items) {
            Object o;
            if (item instanceof Token) {
                Token t = (Token) item;
                o = runtime.variables.get(t.image);
            } else {
                o = item;
            }
            if (visible) {
                stream.print(o);
            } else {
                stream.print(o);
            }
        }
        stream.println();
    }

}
